### ISSUE TITLE
Same result when decimating signal or not

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#93] opened 2018-10-12 00:14 UTC
1. I extracted audio checking "mix to mono" but not "decimate audio?".  File size is much larger, so I do think it correctly did not decimate the audio.
2. Added signal twice using the first 5 minutes of the file, once with "Decimate?" checked and once with it unchecked.
3. Signal appears to be the same in both cases.
![image](https://user-images.githubusercontent.com/42757020/46840676-2c7b5680-cd92-11e8-977d-b030eee6ad34.png)

In both cases the signal is rolling off as it is approaching 500Hz, so I think that it is resampling to 1000Hz either way?  Or is it just a display issue?

**Comment by 3ll3d00d** [comment] 2018-10-12 06:04
I don't understand point 1, pls clarify what you mean (what you expect to happen, what did happen). Please also provide specifics of the input audio track and the resulting output (sample rate etc)

**Comment by 3ll3d00d** [comment] 2018-10-12 07:20
to illustrate point 1

extract audio, no decimate, filter command is a copy

<img width="442" alt="93_1" src="https://user-images.githubusercontent.com/2487509/46854016-97ab4400-cdf7-11e8-8e5a-64307d20b020.png">

resulting audio file, shows as 48kHz

<img width="442" alt="93_2" src="https://user-images.githubusercontent.com/2487509/46854038-a4c83300-cdf7-11e8-9bc0-fbc5caadbf41.png">

extract audio, with decimate, filter command includes resample

<img width="443" alt="93_3" src="https://user-images.githubusercontent.com/2487509/46854063-aeea3180-cdf7-11e8-9ff6-179011828a09.png">

resulting audio file, shows as 1kHz

<img width="442" alt="93_4" src="https://user-images.githubusercontent.com/2487509/46854072-b6113f80-cdf7-11e8-93c2-05d00669d711.png">

**Comment by aron7awol** [comment] 2018-10-12 14:03
![image](https://user-images.githubusercontent.com/42757020/46873351-49507200-ce04-11e8-9610-03a8b51adf40.png)
![image](https://user-images.githubusercontent.com/42757020/46873954-fa0b4100-ce05-11e8-81a6-90397188f168.png)
![image](https://user-images.githubusercontent.com/42757020/46873985-0b544d80-ce06-11e8-9001-cf20f618fb42.png)

Maybe it has something to do with the fact that I selected the first 5 minutes and not the whole track?

**Comment by 3ll3d00d** [comment] 2018-10-12 14:17
I selected a subset of the track too. I will try a few more files to see if I can reproduce.

**Comment by aron7awol** [comment] 2018-10-12 14:34
I just saw your new issue about analysis fs in preferences.  Maybe that is the cause.  I never saw that preference before, so mine was set to 1000Hz.  I will try full range.

**Comment by aron7awol** [comment] 2018-10-12 14:46
Actually, if you don't mind, could you also explain the Resolution setting?  Is that the size of the "buckets" that the frequencies get lumped in for analysis?

**Comment by aron7awol** [comment] 2018-10-12 15:07
I changed that setting and now it seems to work.  The graph limits dialog won't let me go above 500Hz though.

**Comment by 3ll3d00d** [comment] 2018-10-12 18:33
> I just saw your new issue about analysis fs in preferences. Maybe that is the cause. I never saw that preference before, so mine was set to 1000Hz. I will try full range.

#95 refers to the target sample rate when the decimate checkbox is checked in "Extract Audio", that is currently hardcoded to 1000Hz as opposed honouring that preference.

That value is used however when the decimate checkbox is checked on the "Add Signal" screen. If the box is unchecked then the value is ignored. 

the full range option in that dropdown doesn't really make sense now I've added the checkboxes so I'll probably remove that option

**Comment by 3ll3d00d** [comment] 2018-10-12 18:34
> Actually, if you don't mind, could you also explain the Resolution setting? Is that the size of the "buckets" that the frequencies get lumped in for analysis?
yes, it is the time vs frequency resolution basically. You can see this more clearly if you use the spectrogram view that pops out from analyse audio.

**Comment by 3ll3d00d** [comment] 2018-10-12 18:35
> The graph limits dialog won't let me go above 500Hz though.
the dialog doesn't atm, you can change the limits in preferences though and restart the app to see the newly expanded range

**Comment by aron7awol** [comment] 2018-10-12 18:41
After I saw that analysis fs option in preferences, as a test I set it to 2000Hz, and then added the same 48kHz signal **without** checking Decimate? and it displayed at 2000Hz.  So it seems that even when Decimate? is unchecked it is using that setting, which doesn't seem to be the expected behavior according to your explanation above.

**Comment by 3ll3d00d** [comment] 2018-10-12 19:13
The example I gave earlier included an example of me selecting a 48kHz wav with decimate unchecked and seeing that arrive in the main screen as a 48kHz signal

i.e. I cannot reproduce the behaviour seen based on the information provided

This means there is something specific to your method that I'm not doing

** fiddles some more **

The difference is that when "load all channels" is checked then it decimates anyway (NB: in your case it has been checked for you because you've mixed to mono).

the moral of this story is that I should write more tests really but ¯\_(ツ)_/¯

**Closed** 2018-10-12 19:46 UTC
Labels: bug
