### ISSUE TITLE
Optionally apply gain filters to unfiltered line

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#166] opened 2018-12-20 01:56 UTC
I know the whole gain thing isn't something you're interested in spending a lot of time on, so I'm trying to think of the quickest hack that would apply the gain to both lines.  One thought I had was to just add an option that makes all gain filters applied to the unfiltered line.  Is that a quick enough hack that you'd do it?

I appreciate the value of your time so I hate to ask for a feature that you aren't crazy about, but I think we both agree it looks really bad the way I'm publishing now with MV adjustments, and it makes it difficult to see the effect of the rest of the filters, which are the ones we really care about.

**Comment by 3ll3d00d** [comment] 2018-12-20 06:46
This would be messy to implement (which means buggy) so it isn't something I would spend time on

I suggest add the MV adjustment as a title in the report (might need to move that to the bottom) and not add it as a filter. Offset the colour range by that much and the graphs will all look correct.

**Comment by aron7awol** [comment] 2018-12-20 16:07
How about a simple offset that can be applied to the entire plot?  Something like... 
plt.plot(x, y+offset)
?

**Comment by 3ll3d00d** [comment] 2018-12-21 06:47
No sorry, I won't be adding a feature like that.

**Comment by 3ll3d00d** [comment] 2018-12-22 09:30
I took another look at this to see if there is a quick way to add this. I can't see a way to do this cleanly and quickly though. The problem is that the signal and its filters are the core model which is then used to feed the different views. This design is what makes it relatively quick and easy to add things like the waveform view or the bass managed signal. Conversely it is hard, and makes the software brittle (i.e. prone to having odd edge case defects), to add something that doesn't fit the model. This feature is one of those things.

I'll leave this open in case I think of a way to add it in a way that fits the design of the app but I don't expect to implement this any time soon.

**Comment by 3ll3d00d** [comment] 2018-12-22 09:32
as soon as I write that, I realise that the simple implementation is to provide a way to do a permanent change in signal level of the entire signal (in memory)

**Comment by 3ll3d00d** [comment] 2018-12-22 10:37
However note that this will mean you won't see the adjustment anywhere at all (such as the report)

**Comment by aron7awol** [comment] 2018-12-22 14:13
Thank you for looking into reasonable options to make something like this happen!

If you went with that approach, could you also store the value that was applied to the signal, so that it could be undone or displayed later on?

**Comment by 3ll3d00d** [comment] 2018-12-22 14:41
it wouldn't change the signal on disk, just in memory (unless you saved it as a signal file), if this is the concern?

**Comment by aron7awol** [comment] 2018-12-22 14:46
Okay, so I guess undoing it isn't really a concern, then.  I was also thinking if the value were stored (also in memory) it could also be displayed, say in the bottom right corner of the report.

**Comment by 3ll3d00d** [comment] 2018-12-22 17:39
Yes it is possible. I did think of doing it like this but that opens it up to more work. I will see how much time I get to do this.

**Comment by 3ll3d00d** [comment] 2018-12-26 21:32
I've added an offset which can be set when you add a signal and which is shown on the report with a type of MV. 

Note that the value is not editable after the signal is added and making it read only is a shortcut that makes it possible to add this quickly so I don't plan to change this.

**Closed by 3ll3d00d** 2018-12-26 21:32 UTC
Labels: enhancement

**Comment by aron7awol** [comment] 2018-12-27 17:18
Thanks so much for adding this!  I'll test it out.

**Comment by aron7awol** [comment] 2018-12-27 22:18
Just a minor formatting thing, but the MV adjustments seem to display with 2 decimal places always.  Obviously, this isn't a big deal, but for consistency you may want to have it go to 1 decimal place or behave how the other values do.
