### ISSUE TITLE
Report image download from HTTPS URL fails in 0.7.0 beta

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#252] opened 2019-04-26 14:36 UTC
`2019-04-26 10:35:47,270 - ERROR - MainThread	- report - __download_image - Unable to download https://fanart.tv/fanart/movies/102899/moviethumb/ant-man-563e4cee9b65f.jpg
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 588, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 248, in _get_conn
  File "site-packages\urllib3\connectionpool.py", line 816, in _new_conn
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fanart.tv', port=443): Max retries exceeded with url: /fanart/movies/102899/moviethumb/ant-man-563e4cee9b65f.jpg (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model\report.py", line 780, in __download_image
  File "site-packages\requests\api.py", line 75, in get
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='fanart.tv', port=443): Max retries exceeded with url: /fanart/movies/102899/moviethumb/ant-man-563e4cee9b65f.jpg (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))`

**Comment by 3ll3d00d** [comment] 2019-04-26 14:41
Annoying, I thought I had fixed this.

Are you using the small option or the normal one?

**Comment by aron7awol** [comment] 2019-04-26 14:42
Normal

**Comment by 3ll3d00d** [comment] 2019-04-27 10:12
I'm unable to reproduce this

can you try the _small version to see if that one works for you?

**Comment by aron7awol** [comment] 2019-04-27 17:26
I just tried the small version and it is working fine

**Comment by 3ll3d00d** [comment] 2019-04-27 19:52
closing for now as I can't reproduce this, will be interested to know if you feel any performance difference with the _small version though

**Closed by 3ll3d00d** 2019-04-27 19:52 UTC
Labels: can't reproduce
