### ISSUE TITLE
0.9.0 alpha errors out

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#285] opened 2019-07-18 19:41 UTC
```
c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:627: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "site-packages\qtpy\__init__.py", line 202, in <module>
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "model\waveform.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtawesome\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtawesome\iconic_font.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtpy\__init__.py", line 208, in <module>
qtpy.PythonQtError: No Qt bindings could be found
[13284] Failed to execute script app
```

**Comment by aron7awol** [comment] 2019-07-18 19:43
I've been using 0.7.3-beta.2 because every release since then has had similar issues to this one.

**Comment by 3ll3d00d** [comment] 2019-07-18 21:19
and it's still a mystery :-1:

**Comment by aron7awol** [comment] 2019-07-18 21:31
Damn, really?  I figured you had to make a pretty drastic underlying change to get the rough cut of Median working and that was the cause of these issues.

**Comment by 3ll3d00d** [comment] 2019-07-18 22:19
noticed some dependency had changed which I hadn't noticed before which has some bug in it, try https://github.com/3ll3d00d/beqdesigner/releases/tag/0.7.3-beta.5 for the median build

**Comment by aron7awol** [comment] 2019-07-18 23:49
That works much better.  Just found one bug, when trying to edit a filter:

![image](https://user-images.githubusercontent.com/42757020/61499438-2a839b00-a995-11e9-89e8-711aef5abb7e.png)

**Comment by 3ll3d00d** [comment] 2019-07-20 08:37
I can't recreate that, what were you doing exactly?

**Comment by aron7awol** [comment] 2019-07-20 13:09
I just loaded my saved BEQ for Snitch to post the median graph you wanted to see, and if I try to edit either of the filters I get this error.

**Comment by 3ll3d00d** [comment] 2019-07-21 13:53
I still can't reproduce this, can you share the project file for it?

**Comment by aron7awol** [comment] 2019-07-21 13:59
[Snitch.zip](https://github.com/3ll3d00d/beqdesigner/files/3414670/Snitch.zip)

**Comment by 3ll3d00d** [comment] 2019-07-21 14:42
thanks, I can't even open that so obviously that's another bug entirely!

**Comment by aron7awol** [comment] 2019-07-21 19:17
Same error when trying to edit a filter on 0.7.3-beta.9

It must be related to the dependency updates, right? When I go back to beta.2 it works perfectly.

**Comment by 3ll3d00d** [comment] 2019-07-21 20:07
hmm I tried it on another machine and see the error is

    <class 'SystemError'> <built-in function connectSlotsByName> returned a result with an error set <traceback object at 0x0000000A461DD688>

so something in Qt is blowing up

**Comment by 3ll3d00d** [comment] 2019-07-21 20:09
original issue resolved by https://github.com/3ll3d00d/beqdesigner/commit/ecdb68c4d10b1aadabd6db1fe7fac50541d0f36f

**Closed** 2019-07-21 20:08 UTC
Labels: bug
